{{- if .Values.webui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webui
    servicename: webui
{{ include "dockercoins-single.labels" . | indent 4 }}
  name: webui
spec:
  ports:
  - port: {{ .Values.webui.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: webui
  type: NodePort
{{- end }}