{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
    servicename: worker
{{ include "dockercoins-single.labels" . | indent 4 }}
  name: worker
spec:
  replicas: {{ .Values.worker.replicasCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
        name: worker
{{- end }}